# FETCH UNREAD EMAILS FROM GMAIL
# PARSE EACH EMAIL INTO SUBJECT, SENDER, AND BODY

# USE AI TO DETERMINE IF THE EMAIL IS JOB-RELATED
# IGNORE EMAILS THAT ARE NOT RELATED TO JOB APPLICATIONS

# IF THE EMAIL IS JOB-RELATED, SAVE IT TO MYSQL
# MYSQL STORES THE LIVE EMAIL DATA AND AI RESULTS

# USE AI TO CLASSIFY THE EMAIL STATUS
# LABEL THE EMAIL AS "REJECTED" OR "NEXT STEP"

# EXTRACT IMPORTANT DETAILS FROM THE EMAIL
# SUCH AS COMPANY NAME AND JOB TITLE

# USE THE MYSQL RECORD TO FIND THE MATCHING APPLICATION ENTRY
# UPDATE THE SPREADSHEET STATUS DROPDOWN WITH THE AI PREDICTION

# KEEP JSON FILES SEPARATE FOR TRAINING AND TESTING DATA
# USE THEM TO TRAIN, EVALUATE, AND IMPROVE THE AI MODEL